root_folder: machine-learning-28031992

mongodb:
  is_cloud: 1 #0 for local & 1 for cloud
  user_name: sharad28
  password: sharad28
  url: mongodb+srv://{0}:{1}@cluster0.enlme.mongodb.net/myFirstDatabase?retryWrites=true&w=majority

cloud_storage:
  azure_blob_storage:
    connection_str: DefaultEndpointsProtocol=https;AccountName=automationml;AccountKey=qFLEZSSpH9ONZxWQObDAu6rexf+0WSBk/+fipnEYKqzQOo0aKbT7EJBsSagEcqA3/6zpkToAiiTlO1ly7Lv1mw==;EndpointSuffix=core.windows.net
  aws_s3_bucket:
    name: aws_access_key
    Access Key ID: AKIA3VIFBJDOYYLVMN5X
    Secret Access Key: 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
    description: AWS credentials

  gcp: gcp.json
    
watcher_checkpoint_storage_account_connection_str:
  connection_str: DefaultEndpointsProtocol=https;AccountName=storageaccountrgai1a757;AccountKey=j4TYtRYwIDyUNL4lKXXIfYgCftrTbJPhPHC8i/j66XSf6s81ruCaQqDnjh5WDMjrqqc4hulvZ8wxcYQb8KfukA==;EndpointSuffix=core.windows.net

azure_input_file_storage_connection_str:
  connection_str: DefaultEndpointsProtocol=https;AccountName=inputfilestorage;AccountKey=u2jUt3DLgsPiZO8S7kZ1yk4B7FJ6gCtdTeckaige1AXTnyPA1zby1w0n6HUi/2cdOAoo5E1jXrEeofyI6UDtFw==;EndpointSuffix=core.windows.net

event_hub_name_space:
  connection_str: Endpoint=sb://avnish327030.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=BwK0zozJe+Oz46F5BgpHUtq5zkzqMKCzPdc2kOg2WW8=


session:
  secret-key: ec6935d1-0e2c-4998-b7ed-809e8cb0fcda

user_detail:
  email_id: sarad@technip.com
  role_id: 1

email_config:
  sender_email_id: saradmishra28@gmail.com
  passkey: bzrfuaghygsdyckt
  receiver_email_id:
    - saradmishra28@gmail.com
    - sarad.mishra@technipenergies.com